### ISSUE TITLE
uno wifi cant insert data

### ISSUE THREAD

**Issue by komargm** [khoih-prog/MySQL_MariaDB_Generic#7]
Arduino IDE version: 1.8.13
Arduino UNO WIFI rev 2
full spec. https://store.arduino.cc/arduino-uno-wifi-rev2
OS: windows 10
----
MariaDB 10 (on synology NAS)
Arduino connect with wifi but cant insert sample data to database. 
Update code with WIFI ssid/ password. Sql user/password/ip adress/ports/database/

- Create sample database (code from sample code)
 update sketch with wifi /DB
 compiling without problem 
    connect to wifi -OK
    connect to database -OK
    insert data - false

I tray to insert data without fefatult table/valuet. I put full Insert string. without result. 
- I borrowed arduino boart with espp8266 (clone of wemos d1) - all code works grate. 
Where is the problem. 
And in advance I apologize for mistakes, I am a beginner
![2021-08-02 14_50_24-Window](https://user-images.githubusercontent.com/59536137/127871486-6a2754c0-43b6-4446-901d-7e336a65961e.png)
![2021-08-02 15_25_58-Window](https://user-images.githubusercontent.com/59536137/127871489-422fe3a5-7518-4b9f-a015-e6f5af5b9ce6.png)

**Comment by khoih-prog** [comment]
Hi @komargm 

Thanks for your interest in the library. 

> I am a beginner

Your issue report is so good for a beginner, and your approach is also great by testing with an ESP8266 to be sure at least some part of the library and your NAS MariaDB installation are all working.

As you can see in the supported list, **UNO WiFi Rev 2** has not been supported yet, even the compilation is OK. That's why you've seen the `Starting Basic_Insert_WiFiNINA on Unknown Board`

I currently don't have this `outdated but expensive` **UNO WiFi Rev 2** to test, and also have no intention to buy one to test and add support to that board, I just can only suggest the following :

1. Buy a different `cheaper, more powerful and popular` board, such as **ESP8266/ESP32 or even WT32_ETH01**
2. Turn on better debug level in `defines.h`

```
#define _MYSQL_LOGLEVEL_        4
...
#define _WIFININA_LOGLEVEL_     1
```

then post the debug terminal output here, hopefully someone can help and fix the issue.

As I said earlier, I have **no hope to add support to this board** because I have no such a board to debug. I'll close the issue now and will reopen when actually working on it.

Good Luck,
